const emojiToText = {
    "😃": "Grinning Face with Big Eyes",
    "😂": "Face with Tears of Joy",
    "🥲": "Smiling Face with Tear",
    "😍": "Smiling Face with Heart-Eyes",
    "😒": "Unamused Face",
    "😔": "Pensive Face",
    "😡": "Pouting Face",
    "🤯": "Exploding Head",
    "😴": "Sleeping Face",
    "🥳": "Partying Face",
    "😀": "Grinning Face",
    "😄": "Grinning Face with Smiling Eyes",
    "😁": "Beaming Face with Smiling Eyes",
    "😆": "Grinning Squinting Face",
    "😅": "Grinning Face with Sweat",
    "🤣": "Rolling on the Floor Laughing",
    "🙂": "Slightly Smiling Face",
    "🙃": "Upside-Down Face",
    "😉": "Winking Face",
    "😊": "Smiling Face with Smiling Eyes",
    "😇": "Smiling Face with Halo",
    "🥰": "Smiling Face with Hearts",
    "🤩": "Star-Struck",
    "😘": "Face Blowing a Kiss",
    "😗": "Kissing Face",
    "😚": "Kissing Face with Closed Eyes",
    "😋": "Face Savoring Food",
    "😛": "Face with Tongue",
    "😜": "Winking Face with Tongue",
    "🤪": "Zany Face",
    "😝": "Squinting Face with Tongue",
    "🤑": "Money-Mouth Face",
    "🤗": "Hugging Face",
    "🤭": "Face with Hand Over Mouth",
    "🤫": "Shushing Face",
    "🤔": "Thinking Face",
    "🐶": "Dog",
    "🐱": "Cat",
    "🐭": "Mouse",
    "🐹": "Hamster",
    "🐰": "Rabbit",
    "🦊": "Fox",
    "🐻": "Bear",
    "🐼": "Panda",
    "🐨": "Koala",
    "🐯": "Tiger",
    "🦁": "Lion",
    "🐮": "Cow",
    "🐷": "Pig",
    "🐽": "Pig Snout",
    "🐸": "Frog",
    "🐵": "Monkey",
    "🙈": "See-No-Evil Monkey",
    "🙉": "Hear-No-Evil Monkey",
    "🙊": "Speak-No-Evil Monkey",
    "🐒": "Monkey",
    "🐔": "Chicken",
    "🐧": "Penguin",
    "🐦": "Bird",
    "🐤": "Baby Chick",
    "🐣": "Hatching Chick",
    "🐥": "Chick",
    "🦆": "Duck",
    "🦅": "Eagle",
    "🦉": "Owl",
    "🦇": "Bat",
    "🐺": "Wolf",
    "🐗": "Boar",
    "🐴": "Horse",
    "🦄": "Unicorn",
    "🐝": "Bee",
    "🐛": "Bug",
    "🦋": "Butterfly",
    "🐌": "Snail",
    "🐞": "Lady Beetle",
    "🐜": "Ant",
    "🍔": "Hamburger",
    "🍟": "French Fries",
    "🌭": "Hot Dog",
    "🍕": "Pizza Slice",
    "🌮": "Taco",
    "🌯": "Burrito",
    "🥙": "Wrap",
    "🧆": "Falafel",
    "🍲": "Soup",
    "🥗": "Salad",
    "🍣": "Sushi",
    "🍱": "Bento Box",
    "🍛": "Curry Rice",
    "🍜": "Noodles",
    "🍝": "Spaghetti",
    "🍠": "Roasted Sweet Potato",
    "🍤": "Fried Shrimp",
    "🍗": "Chicken Leg",
    "🍖": "Meat on Bone",
    "🥩": "Steak",
    "🥓": "Bacon",
    "🥪": "Sandwich",
    "⚽": "Soccer Ball",
    "🏀": "Basketball",
    "🏈": "American Football",
    "⚾": "Baseball",
    "🥎": "Softball",
    "🎾": "Tennis",
    "🏐": "Volleyball",
    "🏉": "Rugby Football",
    "🎱": "Billiards",
    "🏓": "Ping Pong",
    "🏸": "Badminton",
    "🥏": "Flying Disc",
    "🏑": "Field Hockey",
    "🏒": "Ice Hockey",
    "🏏": "Cricket",
    "🥍": "Lacrosse",
    "🏹": "Bow and Arrow",
    "🎣": "Fishing Pole",
    "⛳️": "Flag in Hole",
    "🥊": "Boxing Glove",
    "🥋": "Martial Arts Uniform",
    "🎽": "Running Shirt",
    "⛸": "Ice Skate",
    "🥌": "Curling Stone",
    "🛷": "Sled",
    "🛹": "Skateboard",
    "🎿": "Skis",
    "⛷": "Skier",
    "🏂": "Snowboarder",
    "🪂": "Parachute",
    "🏋️‍♀️": "Weightlifting (Female)",
    "🏋️‍♂️": "Weightlifting (Male)",
    "🤼‍♀️": "Wrestling (Female)",
    "🤼‍♂️": "Wrestling (Male)",
    "🤸‍♀️": "Cartwheel (Female)",
    "🤸‍♂️": "Cartwheel (Male)",
    "⛹️‍♀️": "Basketball (Female)",
    "⛹️‍♂️": "Basketball (Male)",
    "🤺": "Fencing",
    "🤾‍♀️": "Handball (Female)",
    "✈️": "Airplane",
    "🚀": "Rocket",
    "🚁": "Helicopter",
    "🛸": "Flying Saucer",
    "🚲": "Bicycle",
    "🛴": "Scooter",
    "🛹": "Skateboard",
    "🛵": "Motor Scooter",
    "🚗": "Car",
    "🚕": "Taxi",
    "🚙": "Sport Utility Vehicle",
    "🚌": "Bus",
    "🚎": "Trolleybus",
    "🏎": "Racing Car",
    "🚓": "Police Car",
    "🚑": "Ambulance",
    "🚒": "Fire Engine",
    "🚐": "Minibus",
    "🚚": "Delivery Truck",
    "🚛": "Articulated Lorry",
    "🚜": "Tractor",
    "🛺": "Auto Rickshaw",
    "🚍": "Oncoming Bus",
    "🚘": "Oncoming Automobile",
    "🚖": "Oncoming Taxi",
    "🛻": "Pickup Truck",
    "🚔": "Police Car Light",
    "🚡": "Aerial Tramway",
    "🚠": "Mountain Cableway",
    "🚃": "Railway Car",
    "🚂": "Locomotive",
    "🚆": "Train",
    "🚄": "High-Speed Train",
    "🚅": "Bullet Train",
    "🚈": "Light Rail",
    "🚝": "Monorail",
    "🚞": "Mountain Railway",
    "🚋": "Tram Car",
    "🚊": "Tram",
    "🚉": "Railway Track",
    "💡": "Lightbulb",
    "🔦": "Flashlight",
    "🕯️": "Candle",
    "🪔": "Diya Lamp",
    "🧯": "Fire Extinguisher",
    "🛢️": "Oil Drum",
    "💣": "Bomb",
    "🧨": "Firecracker",
    "🪓": "Axe",
    "🔪": "Kitchen Knife",
    "🗡️": "Dagger",
    "⚔️": "Crossed Swords",
    "🛡️": "Shield",
    "🚪": "Door",
    "🛋️": "Couch and Lamp",
    "🛏️": "Bed",
    "🪑": "Chair",
    "🚽": "Toilet",
    "🚿": "Shower",
    "🛁": "Bathtub",
    "🧼": "Soap",
    "🧽": "Sponge",
    "🧴": "Lotion Bottle",
    "🪒": "Razor",
    "🧹": "Broom",
    "🧺": "Basket",
    "♾️": "Infinity",
    "🎲": "Game Die",
    "🎯": "Direct Hit",
    "🎳": "Bowling",
    "🎮": "Video Game",
    "🎰": "Slot Machine",
    "🧩": "Puzzle Piece",
    "🎨": "Artist Palette",
    "🧵": "Thread",
    "🧶": "Yarn",
    "📚": "Books",
    "📖": "Open Book",
    "📔": "Notebook",
    "📒": "Ledger",
    "📑": "Bookmark Tabs",
    "📓": "Notebook with Decorative Cover",
    "📃": "Page with Curl",
    "📜": "Scroll",
    "📄": "Page Facing Up",
    "📰": "Newspaper",
    "🗞️": "Rolled-Up Newspaper",
    "🔖": "Bookmark",
    "🏷️": "Label",
    "💰": "Money Bag",
    "💴": "Yen Banknote",
    "💵": "Dollar Banknote",
    "💶": "Euro Banknote",
    "💷": "Pound Banknote",
    "💸": "Money with Wings",
    "💳": "Credit Card",
    "💎": "Gem Stone",
    "⚖️": "Balance Scale",
    "🧰": "Toolbox",
    "🔨": "Hammer",
    "⛏️": "Pick",
    "⚒️": "Hammer and Pick",
    "🛠️": "Hammer and Wrench",
    "🗡️": "Dagger",
    "⚔️": "Crossed Swords",
    "🏳️": "Waving Flag",
    "🏴": "Black Flag",
    "🏁": "Chequered Flag",
    "🚩": "Triangular Flag",
    "🏳️‍🌈": "Rainbow Flag",
    "🏴‍☠️": "Pirate Flag",
};

export default emojiToText;
